---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-match-end
spec:
  broker: default
  filter:
    attributes:
      type: match-end
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: matchend

